/* Generated by Together */

package com.javapatterns.command.drawapplet;

public class AddLineCommand implements Command {
   /**
    * @supplierRole drawing 
    */
   private Drawing    drawing;

   /**
    * @supplierRole line 
    */
   private Line       line;

  public AddLineCommand( Drawing targetDrawing, Line newLine ) {
       drawing = targetDrawing;
       line = newLine;
  }

  public void execute() {
       drawing.add( line );
  }

  public void unexecute() {
       drawing.remove( line );
  }

  public boolean canExecute() {
       return true;
  }

  public boolean canUnexecute() {
       return true;
  }
}

