/* Generated by Together */

package com.javapatterns.facade.sessionfacade;

import java.rmi.RemoteException;

import javax.ejb.CreateException;
import javax.ejb.EJBException;
import javax.ejb.SessionBean;
import javax.ejb.SessionContext;

/**
 * @ejbHome <{com.javapatterns.facade.sessionfacade.Business2Home}>
 * @ejbRemote <{com.javapatterns.facade.sessionfacade.Business2}>
 * @ejbStateful 
 */
public class Business2Bean implements SessionBean {
    private SessionContext ctx;

    public void setSessionContext(SessionContext context) throws RemoteException, EJBException {
        ctx = context;
    }

    public void ejbActivate() throws RemoteException, EJBException {
    }

    public void ejbPassivate() throws RemoteException, EJBException {
    }

    public void ejbRemove() throws RemoteException, EJBException {
    }

    public void ejbCreate() throws CreateException, EJBException, RemoteException {
            // Write your code here
        }

    public void BusinessMethod1() {
    }

    public void BusinessMethod2() {
    }
}
