/* Generated by Together */

package com.javapatterns.facade.sessionfacade;

public class Client {
    /**
     * @label Uses
     * @directed 
     */
    private SessionFacadeBean lnkSessionFacadeBean;
}
