/* Generated by Together */

package com.javapatterns.facade.sessionfacade;

import java.rmi.RemoteException;

import javax.ejb.CreateException;
import javax.ejb.EJBException;
import javax.ejb.SessionBean;
import javax.ejb.SessionContext;

/**
 * @ejbHome <{com.javapatterns.facade.sessionfacade.SessionFacadeHome}>
 * @ejbRemote <{com.javapatterns.facade.sessionfacade.SessionFacade}>
 * @ejbStateful*/
public class SessionFacadeBean implements SessionBean {
    private SessionContext ctx;

    /**
     * @directed
     * @link aggregation 
     */
    private Business1Bean lnkBusiness1Bean;

    /**
     * @directed
     * @link aggregation 
     */
    private Business2Bean lnkBusiness2Bean;

    public void setSessionContext(SessionContext context) throws RemoteException, EJBException {
        ctx = context;
    }

    public void ejbActivate() throws RemoteException, EJBException {
    }

    public void ejbPassivate() throws RemoteException, EJBException {
    }

    public void ejbRemove() throws RemoteException, EJBException {
    }

    public void ejbCreate() throws CreateException, EJBException, RemoteException {
            // Write your code here
        }

    public void BusinessMethod1() throws RemoteException, EJBException  {
    }

    public void BusinessMethod2() {
    }
}
