/* Generated by Together */

package com.javapatterns.facade.sessionfacade;

import java.rmi.RemoteException;

import javax.ejb.CreateException;
import javax.ejb.EJBException;
import javax.ejb.EJBHome;

public interface SessionFacadeHome extends EJBHome {
SessionFacade create() throws CreateException, EJBException, RemoteException;

    /** @link dependency */
    /*#SessionFacadeBean lnkSession1Bean;*/
}
