/* Generated by Together */

package com.javapatterns.composite.filesystem;

public class FileNode extends FileSystemNode {
    public FileNode() {
    }

    public int getSize() {  return 0;
    }
}
