/* Generated by Together */

package com.javapatterns.observer.javautil;

import java.util.Observable;
public class ConcreteObservable extends Observable {
    /**
     * @directed
     * @label setChanged() 
     */
    private Observable lnkObservable;

    /**
     * @directed
     * @label notifyObservers()*/
    private Observable lnkObservable1;
}
