GNUSTEP_MAKEFILES=/GNUstep/System/Library/Makefiles

include $(GNUSTEP_MAKEFILES)/common.make
APP_NAME=Stud
##(APP_NAME)_HEADERS=Stud.h
##$(APP_NAME)_OBJC_FILES=Stud.m main.m
$(APP_NAME)_OBJC_FILES=main.m
##$(APP_NAME)_RESOURCE_FILES=
include $(GNUSTEP_MAKEFILES)/application.make