/* Generated by Together */

package com.javapatterns.isp.altavista;

public class RdbIndexer implements Indexer
{
    public void reIndexAll()
    {
    	//write your code here
    }

    public void updateIndex()
    {
    	//write your code here
    }
}
