/* Generated by Together */

package com.javapatterns.prototype.cad;

public class Client
{
    public static void main(String[] args)
    {
		CadSymbolManager csm = new CadSymbolManager();
		CadSymbolLoader csl = new CadSymbolLoader(csm);

        String fname = "fancyfont";
        csl.loadCadSymbols(fname);
    }
}
