/* Generated by Together */

package com.javapatterns.memento.wideandnarrow1;

public class User {
    /** @link dependency */
    /*#Wide lnkWide;*/

    /** @link dependency */
    /*#ConcreteClass lnkConcreteClass;*/
}
