/* Generated by Together */

package com.javapatterns.command.television;

public interface Invoker {
    void invoke();

    /**
     * @link aggregation
     * @directed 
     */
    /*#Command lnkCommand;*/
}
